//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 03:28:59 PM CEST 
//


package org.mycore.xml.alto.v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MeasurementUnit" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="pixel"/>
 *                         &lt;enumeration value="mm10"/>
 *                         &lt;enumeration value="inch1200"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="sourceImageInformation" type="{http://www.loc.gov/standards/alto/ns-v2#}sourceImageInformationType" minOccurs="0"/>
 *                   &lt;element name="OCRProcessing" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.loc.gov/standards/alto/ns-v2#}ocrProcessingType">
 *                           &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Styles" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TextStyle" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{http://www.loc.gov/standards/alto/ns-v2#}formattingAttributeGroup"/>
 *                           &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ParagraphStyle" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="ALIGN">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="Left"/>
 *                                 &lt;enumeration value="Right"/>
 *                                 &lt;enumeration value="Center"/>
 *                                 &lt;enumeration value="Block"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="LEFT" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="RIGHT" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="LINESPACE" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="FIRSTLINE" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Layout">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Page" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TopMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
 *                             &lt;element name="LeftMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
 *                             &lt;element name="RightMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
 *                             &lt;element name="BottomMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
 *                             &lt;element name="PrintSpace" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="PAGECLASS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="STYLEREFS" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *                           &lt;attribute name="HEIGHT" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="WIDTH" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="PHYSICAL_IMG_NR" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="PRINTED_IMG_NR" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="QUALITY">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="OK"/>
 *                                 &lt;enumeration value="Missing"/>
 *                                 &lt;enumeration value="Missing in original"/>
 *                                 &lt;enumeration value="Damaged"/>
 *                                 &lt;enumeration value="Retained"/>
 *                                 &lt;enumeration value="Target"/>
 *                                 &lt;enumeration value="As in original"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="QUALITY_DETAIL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="POSITION">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="Left"/>
 *                                 &lt;enumeration value="Right"/>
 *                                 &lt;enumeration value="Foldout"/>
 *                                 &lt;enumeration value="Single"/>
 *                                 &lt;enumeration value="Cover"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="PROCESSING" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="ACCURACY" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="PC">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                                 &lt;minInclusive value="0"/>
 *                                 &lt;maxInclusive value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="STYLEREFS" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "styles",
    "layout"
})
@XmlRootElement(name = "alto")
public class Alto {

    @XmlElement(name = "Description")
    protected Alto.Description description;
    @XmlElement(name = "Styles")
    protected Alto.Styles styles;
    @XmlElement(name = "Layout", required = true)
    protected Alto.Layout layout;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Alto.Description }
     *     
     */
    public Alto.Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alto.Description }
     *     
     */
    public void setDescription(Alto.Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the styles property.
     * 
     * @return
     *     possible object is
     *     {@link Alto.Styles }
     *     
     */
    public Alto.Styles getStyles() {
        return styles;
    }

    /**
     * Sets the value of the styles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alto.Styles }
     *     
     */
    public void setStyles(Alto.Styles value) {
        this.styles = value;
    }

    /**
     * Gets the value of the layout property.
     * 
     * @return
     *     possible object is
     *     {@link Alto.Layout }
     *     
     */
    public Alto.Layout getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alto.Layout }
     *     
     */
    public void setLayout(Alto.Layout value) {
        this.layout = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MeasurementUnit" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="pixel"/>
     *               &lt;enumeration value="mm10"/>
     *               &lt;enumeration value="inch1200"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="sourceImageInformation" type="{http://www.loc.gov/standards/alto/ns-v2#}sourceImageInformationType" minOccurs="0"/>
     *         &lt;element name="OCRProcessing" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.loc.gov/standards/alto/ns-v2#}ocrProcessingType">
     *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "measurementUnit",
        "sourceImageInformation",
        "ocrProcessing"
    })
    public static class Description {

        @XmlElement(name = "MeasurementUnit")
        protected String measurementUnit;
        protected SourceImageInformationType sourceImageInformation;
        @XmlElement(name = "OCRProcessing")
        protected List<Alto.Description.OCRProcessing> ocrProcessing;

        /**
         * Gets the value of the measurementUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMeasurementUnit() {
            return measurementUnit;
        }

        /**
         * Sets the value of the measurementUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMeasurementUnit(String value) {
            this.measurementUnit = value;
        }

        /**
         * Gets the value of the sourceImageInformation property.
         * 
         * @return
         *     possible object is
         *     {@link SourceImageInformationType }
         *     
         */
        public SourceImageInformationType getSourceImageInformation() {
            return sourceImageInformation;
        }

        /**
         * Sets the value of the sourceImageInformation property.
         * 
         * @param value
         *     allowed object is
         *     {@link SourceImageInformationType }
         *     
         */
        public void setSourceImageInformation(SourceImageInformationType value) {
            this.sourceImageInformation = value;
        }

        /**
         * Gets the value of the ocrProcessing property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ocrProcessing property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOCRProcessing().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Alto.Description.OCRProcessing }
         * 
         * 
         */
        public List<Alto.Description.OCRProcessing> getOCRProcessing() {
            if (ocrProcessing == null) {
                ocrProcessing = new ArrayList<Alto.Description.OCRProcessing>();
            }
            return this.ocrProcessing;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.loc.gov/standards/alto/ns-v2#}ocrProcessingType">
         *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class OCRProcessing
            extends OcrProcessingType
        {

            @XmlAttribute(name = "ID", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setID(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Page" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TopMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
     *                   &lt;element name="LeftMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
     *                   &lt;element name="RightMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
     *                   &lt;element name="BottomMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
     *                   &lt;element name="PrintSpace" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="PAGECLASS" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="STYLEREFS" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
     *                 &lt;attribute name="HEIGHT" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="WIDTH" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="PHYSICAL_IMG_NR" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="PRINTED_IMG_NR" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="QUALITY">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="OK"/>
     *                       &lt;enumeration value="Missing"/>
     *                       &lt;enumeration value="Missing in original"/>
     *                       &lt;enumeration value="Damaged"/>
     *                       &lt;enumeration value="Retained"/>
     *                       &lt;enumeration value="Target"/>
     *                       &lt;enumeration value="As in original"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="QUALITY_DETAIL" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="POSITION">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="Left"/>
     *                       &lt;enumeration value="Right"/>
     *                       &lt;enumeration value="Foldout"/>
     *                       &lt;enumeration value="Single"/>
     *                       &lt;enumeration value="Cover"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="PROCESSING" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *                 &lt;attribute name="ACCURACY" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="PC">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
     *                       &lt;minInclusive value="0"/>
     *                       &lt;maxInclusive value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="STYLEREFS" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "page"
    })
    public static class Layout {

        @XmlElement(name = "Page", required = true)
        protected List<Alto.Layout.Page> page;
        @XmlAttribute(name = "STYLEREFS")
        @XmlIDREF
        @XmlSchemaType(name = "IDREFS")
        protected List<Object> stylerefs;

        /**
         * Gets the value of the page property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the page property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Alto.Layout.Page }
         * 
         * 
         */
        public List<Alto.Layout.Page> getPage() {
            if (page == null) {
                page = new ArrayList<Alto.Layout.Page>();
            }
            return this.page;
        }

        /**
         * Gets the value of the stylerefs property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stylerefs property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSTYLEREFS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getSTYLEREFS() {
            if (stylerefs == null) {
                stylerefs = new ArrayList<Object>();
            }
            return this.stylerefs;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TopMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
         *         &lt;element name="LeftMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
         *         &lt;element name="RightMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
         *         &lt;element name="BottomMargin" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
         *         &lt;element name="PrintSpace" type="{http://www.loc.gov/standards/alto/ns-v2#}PageSpaceType" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="PAGECLASS" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="STYLEREFS" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
         *       &lt;attribute name="HEIGHT" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="WIDTH" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="PHYSICAL_IMG_NR" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="PRINTED_IMG_NR" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="QUALITY">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="OK"/>
         *             &lt;enumeration value="Missing"/>
         *             &lt;enumeration value="Missing in original"/>
         *             &lt;enumeration value="Damaged"/>
         *             &lt;enumeration value="Retained"/>
         *             &lt;enumeration value="Target"/>
         *             &lt;enumeration value="As in original"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="QUALITY_DETAIL" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="POSITION">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="Left"/>
         *             &lt;enumeration value="Right"/>
         *             &lt;enumeration value="Foldout"/>
         *             &lt;enumeration value="Single"/>
         *             &lt;enumeration value="Cover"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="PROCESSING" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
         *       &lt;attribute name="ACCURACY" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="PC">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
         *             &lt;minInclusive value="0"/>
         *             &lt;maxInclusive value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "topMargin",
            "leftMargin",
            "rightMargin",
            "bottomMargin",
            "printSpace"
        })
        public static class Page {

            @XmlElement(name = "TopMargin")
            protected PageSpaceType topMargin;
            @XmlElement(name = "LeftMargin")
            protected PageSpaceType leftMargin;
            @XmlElement(name = "RightMargin")
            protected PageSpaceType rightMargin;
            @XmlElement(name = "BottomMargin")
            protected PageSpaceType bottomMargin;
            @XmlElement(name = "PrintSpace")
            protected PageSpaceType printSpace;
            @XmlAttribute(name = "ID", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;
            @XmlAttribute(name = "PAGECLASS")
            protected String pageclass;
            @XmlAttribute(name = "STYLEREFS")
            @XmlIDREF
            @XmlSchemaType(name = "IDREFS")
            protected List<Object> stylerefs;
            @XmlAttribute(name = "HEIGHT")
            protected Integer height;
            @XmlAttribute(name = "WIDTH")
            protected Integer width;
            @XmlAttribute(name = "PHYSICAL_IMG_NR", required = true)
            protected int physicalimgnr;
            @XmlAttribute(name = "PRINTED_IMG_NR")
            protected String printedimgnr;
            @XmlAttribute(name = "QUALITY")
            protected String quality;
            @XmlAttribute(name = "QUALITY_DETAIL")
            protected String qualitydetail;
            @XmlAttribute(name = "POSITION")
            protected String position;
            @XmlAttribute(name = "PROCESSING")
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object processing;
            @XmlAttribute(name = "ACCURACY")
            protected Float accuracy;
            @XmlAttribute(name = "PC")
            protected Float pc;

            /**
             * Gets the value of the topMargin property.
             * 
             * @return
             *     possible object is
             *     {@link PageSpaceType }
             *     
             */
            public PageSpaceType getTopMargin() {
                return topMargin;
            }

            /**
             * Sets the value of the topMargin property.
             * 
             * @param value
             *     allowed object is
             *     {@link PageSpaceType }
             *     
             */
            public void setTopMargin(PageSpaceType value) {
                this.topMargin = value;
            }

            /**
             * Gets the value of the leftMargin property.
             * 
             * @return
             *     possible object is
             *     {@link PageSpaceType }
             *     
             */
            public PageSpaceType getLeftMargin() {
                return leftMargin;
            }

            /**
             * Sets the value of the leftMargin property.
             * 
             * @param value
             *     allowed object is
             *     {@link PageSpaceType }
             *     
             */
            public void setLeftMargin(PageSpaceType value) {
                this.leftMargin = value;
            }

            /**
             * Gets the value of the rightMargin property.
             * 
             * @return
             *     possible object is
             *     {@link PageSpaceType }
             *     
             */
            public PageSpaceType getRightMargin() {
                return rightMargin;
            }

            /**
             * Sets the value of the rightMargin property.
             * 
             * @param value
             *     allowed object is
             *     {@link PageSpaceType }
             *     
             */
            public void setRightMargin(PageSpaceType value) {
                this.rightMargin = value;
            }

            /**
             * Gets the value of the bottomMargin property.
             * 
             * @return
             *     possible object is
             *     {@link PageSpaceType }
             *     
             */
            public PageSpaceType getBottomMargin() {
                return bottomMargin;
            }

            /**
             * Sets the value of the bottomMargin property.
             * 
             * @param value
             *     allowed object is
             *     {@link PageSpaceType }
             *     
             */
            public void setBottomMargin(PageSpaceType value) {
                this.bottomMargin = value;
            }

            /**
             * Gets the value of the printSpace property.
             * 
             * @return
             *     possible object is
             *     {@link PageSpaceType }
             *     
             */
            public PageSpaceType getPrintSpace() {
                return printSpace;
            }

            /**
             * Sets the value of the printSpace property.
             * 
             * @param value
             *     allowed object is
             *     {@link PageSpaceType }
             *     
             */
            public void setPrintSpace(PageSpaceType value) {
                this.printSpace = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setID(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the pageclass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPAGECLASS() {
                return pageclass;
            }

            /**
             * Sets the value of the pageclass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPAGECLASS(String value) {
                this.pageclass = value;
            }

            /**
             * Gets the value of the stylerefs property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the stylerefs property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSTYLEREFS().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Object }
             * 
             * 
             */
            public List<Object> getSTYLEREFS() {
                if (stylerefs == null) {
                    stylerefs = new ArrayList<Object>();
                }
                return this.stylerefs;
            }

            /**
             * Gets the value of the height property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getHEIGHT() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setHEIGHT(Integer value) {
                this.height = value;
            }

            /**
             * Gets the value of the width property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getWIDTH() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setWIDTH(Integer value) {
                this.width = value;
            }

            /**
             * Gets the value of the physicalimgnr property.
             * 
             */
            public int getPHYSICALIMGNR() {
                return physicalimgnr;
            }

            /**
             * Sets the value of the physicalimgnr property.
             * 
             */
            public void setPHYSICALIMGNR(int value) {
                this.physicalimgnr = value;
            }

            /**
             * Gets the value of the printedimgnr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPRINTEDIMGNR() {
                return printedimgnr;
            }

            /**
             * Sets the value of the printedimgnr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPRINTEDIMGNR(String value) {
                this.printedimgnr = value;
            }

            /**
             * Gets the value of the quality property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQUALITY() {
                return quality;
            }

            /**
             * Sets the value of the quality property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQUALITY(String value) {
                this.quality = value;
            }

            /**
             * Gets the value of the qualitydetail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQUALITYDETAIL() {
                return qualitydetail;
            }

            /**
             * Sets the value of the qualitydetail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQUALITYDETAIL(String value) {
                this.qualitydetail = value;
            }

            /**
             * Gets the value of the position property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPOSITION() {
                return position;
            }

            /**
             * Sets the value of the position property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPOSITION(String value) {
                this.position = value;
            }

            /**
             * Gets the value of the processing property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getPROCESSING() {
                return processing;
            }

            /**
             * Sets the value of the processing property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setPROCESSING(Object value) {
                this.processing = value;
            }

            /**
             * Gets the value of the accuracy property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getACCURACY() {
                return accuracy;
            }

            /**
             * Sets the value of the accuracy property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setACCURACY(Float value) {
                this.accuracy = value;
            }

            /**
             * Gets the value of the pc property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getPC() {
                return pc;
            }

            /**
             * Sets the value of the pc property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setPC(Float value) {
                this.pc = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TextStyle" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://www.loc.gov/standards/alto/ns-v2#}formattingAttributeGroup"/>
     *                 &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ParagraphStyle" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="ALIGN">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="Left"/>
     *                       &lt;enumeration value="Right"/>
     *                       &lt;enumeration value="Center"/>
     *                       &lt;enumeration value="Block"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="LEFT" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="RIGHT" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="LINESPACE" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="FIRSTLINE" type="{http://www.w3.org/2001/XMLSchema}float" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "textStyle",
        "paragraphStyle"
    })
    public static class Styles {

        @XmlElement(name = "TextStyle")
        protected List<Alto.Styles.TextStyle> textStyle;
        @XmlElement(name = "ParagraphStyle")
        protected List<Alto.Styles.ParagraphStyle> paragraphStyle;

        /**
         * Gets the value of the textStyle property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the textStyle property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTextStyle().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Alto.Styles.TextStyle }
         * 
         * 
         */
        public List<Alto.Styles.TextStyle> getTextStyle() {
            if (textStyle == null) {
                textStyle = new ArrayList<Alto.Styles.TextStyle>();
            }
            return this.textStyle;
        }

        /**
         * Gets the value of the paragraphStyle property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the paragraphStyle property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParagraphStyle().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Alto.Styles.ParagraphStyle }
         * 
         * 
         */
        public List<Alto.Styles.ParagraphStyle> getParagraphStyle() {
            if (paragraphStyle == null) {
                paragraphStyle = new ArrayList<Alto.Styles.ParagraphStyle>();
            }
            return this.paragraphStyle;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="ALIGN">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="Left"/>
         *             &lt;enumeration value="Right"/>
         *             &lt;enumeration value="Center"/>
         *             &lt;enumeration value="Block"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="LEFT" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="RIGHT" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="LINESPACE" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="FIRSTLINE" type="{http://www.w3.org/2001/XMLSchema}float" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ParagraphStyle {

            @XmlAttribute(name = "ID", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;
            @XmlAttribute(name = "ALIGN")
            protected String align;
            @XmlAttribute(name = "LEFT")
            protected Float left;
            @XmlAttribute(name = "RIGHT")
            protected Float right;
            @XmlAttribute(name = "LINESPACE")
            protected Float linespace;
            @XmlAttribute(name = "FIRSTLINE")
            protected Float firstline;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setID(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the align property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getALIGN() {
                return align;
            }

            /**
             * Sets the value of the align property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setALIGN(String value) {
                this.align = value;
            }

            /**
             * Gets the value of the left property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getLEFT() {
                return left;
            }

            /**
             * Sets the value of the left property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setLEFT(Float value) {
                this.left = value;
            }

            /**
             * Gets the value of the right property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getRIGHT() {
                return right;
            }

            /**
             * Sets the value of the right property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setRIGHT(Float value) {
                this.right = value;
            }

            /**
             * Gets the value of the linespace property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getLINESPACE() {
                return linespace;
            }

            /**
             * Sets the value of the linespace property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setLINESPACE(Float value) {
                this.linespace = value;
            }

            /**
             * Gets the value of the firstline property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getFIRSTLINE() {
                return firstline;
            }

            /**
             * Sets the value of the firstline property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setFIRSTLINE(Float value) {
                this.firstline = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://www.loc.gov/standards/alto/ns-v2#}formattingAttributeGroup"/>
         *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class TextStyle {

            @XmlAttribute(name = "ID")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;
            @XmlAttribute(name = "FONTFAMILY")
            protected String fontfamily;
            @XmlAttribute(name = "FONTTYPE")
            protected FontTypeType fonttype;
            @XmlAttribute(name = "FONTWIDTH")
            protected FontWidthType fontwidth;
            @XmlAttribute(name = "FONTSIZE", required = true)
            protected float fontsize;
            @XmlAttribute(name = "FONTCOLOR")
            @XmlJavaTypeAdapter(HexBinaryAdapter.class)
            @XmlSchemaType(name = "hexBinary")
            protected byte[] fontcolor;
            @XmlAttribute(name = "FONTSTYLE")
            protected List<String> fontstyle;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setID(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the fontfamily property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFONTFAMILY() {
                return fontfamily;
            }

            /**
             * Sets the value of the fontfamily property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFONTFAMILY(String value) {
                this.fontfamily = value;
            }

            /**
             * Gets the value of the fonttype property.
             * 
             * @return
             *     possible object is
             *     {@link FontTypeType }
             *     
             */
            public FontTypeType getFONTTYPE() {
                return fonttype;
            }

            /**
             * Sets the value of the fonttype property.
             * 
             * @param value
             *     allowed object is
             *     {@link FontTypeType }
             *     
             */
            public void setFONTTYPE(FontTypeType value) {
                this.fonttype = value;
            }

            /**
             * Gets the value of the fontwidth property.
             * 
             * @return
             *     possible object is
             *     {@link FontWidthType }
             *     
             */
            public FontWidthType getFONTWIDTH() {
                return fontwidth;
            }

            /**
             * Sets the value of the fontwidth property.
             * 
             * @param value
             *     allowed object is
             *     {@link FontWidthType }
             *     
             */
            public void setFONTWIDTH(FontWidthType value) {
                this.fontwidth = value;
            }

            /**
             * Gets the value of the fontsize property.
             * 
             */
            public float getFONTSIZE() {
                return fontsize;
            }

            /**
             * Sets the value of the fontsize property.
             * 
             */
            public void setFONTSIZE(float value) {
                this.fontsize = value;
            }

            /**
             * Gets the value of the fontcolor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public byte[] getFONTCOLOR() {
                return fontcolor;
            }

            /**
             * Sets the value of the fontcolor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFONTCOLOR(byte[] value) {
                this.fontcolor = value;
            }

            /**
             * Gets the value of the fontstyle property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the fontstyle property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFONTSTYLE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getFONTSTYLE() {
                return this.fontstyle;
            }

            public void addFONTSTYLE(String style) {
                if(this.fontstyle == null) {
                    this.fontstyle = new ArrayList<>();
                }
                this.fontstyle.add(style);
            }

            public void setFONTSTYLE(List<String> fontstyle) {
                this.fontstyle = fontstyle;
            }
            
        }

    }

}
