//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 03:28:59 PM CEST 
//


package org.mycore.xml.alto.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * An ellipse shape.
 * 
 * <p>Java class for EllipseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EllipseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="HPOS" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="VPOS" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HLENGTH" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="VLENGTH" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EllipseType")
public class EllipseType {

    @XmlAttribute(name = "HPOS")
    @XmlSchemaType(name = "anySimpleType")
    protected String hpos;
    @XmlAttribute(name = "VPOS")
    @XmlSchemaType(name = "anySimpleType")
    protected String vpos;
    @XmlAttribute(name = "HLENGTH")
    @XmlSchemaType(name = "anySimpleType")
    protected String hlength;
    @XmlAttribute(name = "VLENGTH")
    @XmlSchemaType(name = "anySimpleType")
    protected String vlength;

    /**
     * Gets the value of the hpos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPOS() {
        return hpos;
    }

    /**
     * Sets the value of the hpos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPOS(String value) {
        this.hpos = value;
    }

    /**
     * Gets the value of the vpos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVPOS() {
        return vpos;
    }

    /**
     * Sets the value of the vpos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVPOS(String value) {
        this.vpos = value;
    }

    /**
     * Gets the value of the hlength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHLENGTH() {
        return hlength;
    }

    /**
     * Sets the value of the hlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHLENGTH(String value) {
        this.hlength = value;
    }

    /**
     * Gets the value of the vlength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVLENGTH() {
        return vlength;
    }

    /**
     * Sets the value of the vlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVLENGTH(String value) {
        this.vlength = value;
    }

}
