//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 01:41:32 PM CEST 
//


package org.mycore.xml.abbyy.v10;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharParamsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="charRecVariants" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="charRecVariant" type="{http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml}CharRecognitionVariant" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="l" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="t" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="r" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="b" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="suspicious" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="proofed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="wordStart" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="wordFirst" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="wordLeftMost" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="wordFromDictionary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="wordNormal" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="wordNumeric" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="wordIdentifier" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="charConfidence" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="serifProbability" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="wordPenalty" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="meanStrokeWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="characterHeight" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="hasUncertainHeight" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="baseLine" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="isTab" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharParamsType", propOrder = {
    "content"
})
public class CharParamsType {

    @XmlElementRef(name = "charRecVariants", namespace = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", type = JAXBElement.class, required = false)
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "l", required = true)
    protected BigInteger l;
    @XmlAttribute(name = "t", required = true)
    protected BigInteger t;
    @XmlAttribute(name = "r", required = true)
    protected BigInteger r;
    @XmlAttribute(name = "b", required = true)
    protected BigInteger b;
    @XmlAttribute(name = "suspicious")
    protected Boolean suspicious;
    @XmlAttribute(name = "proofed")
    protected Boolean proofed;
    @XmlAttribute(name = "wordStart")
    protected Boolean wordStart;
    @XmlAttribute(name = "wordFirst")
    protected Boolean wordFirst;
    @XmlAttribute(name = "wordLeftMost")
    protected Boolean wordLeftMost;
    @XmlAttribute(name = "wordFromDictionary")
    protected Boolean wordFromDictionary;
    @XmlAttribute(name = "wordNormal")
    protected Boolean wordNormal;
    @XmlAttribute(name = "wordNumeric")
    protected Boolean wordNumeric;
    @XmlAttribute(name = "wordIdentifier")
    protected Boolean wordIdentifier;
    @XmlAttribute(name = "charConfidence")
    protected BigInteger charConfidence;
    @XmlAttribute(name = "serifProbability")
    protected BigInteger serifProbability;
    @XmlAttribute(name = "wordPenalty")
    protected BigInteger wordPenalty;
    @XmlAttribute(name = "meanStrokeWidth")
    protected BigInteger meanStrokeWidth;
    @XmlAttribute(name = "characterHeight")
    protected BigInteger characterHeight;
    @XmlAttribute(name = "hasUncertainHeight")
    protected Boolean hasUncertainHeight;
    @XmlAttribute(name = "baseLine")
    protected BigInteger baseLine;
    @XmlAttribute(name = "isTab")
    protected Boolean isTab;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link JAXBElement }{@code <}{@link CharParamsType.CharRecVariants }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the l property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getL() {
        return l;
    }

    /**
     * Sets the value of the l property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setL(BigInteger value) {
        this.l = value;
    }

    /**
     * Gets the value of the t property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getT() {
        return t;
    }

    /**
     * Sets the value of the t property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setT(BigInteger value) {
        this.t = value;
    }

    /**
     * Gets the value of the r property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setR(BigInteger value) {
        this.r = value;
    }

    /**
     * Gets the value of the b property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setB(BigInteger value) {
        this.b = value;
    }

    /**
     * Gets the value of the suspicious property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSuspicious() {
        if (suspicious == null) {
            return false;
        } else {
            return suspicious;
        }
    }

    /**
     * Sets the value of the suspicious property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSuspicious(Boolean value) {
        this.suspicious = value;
    }

    /**
     * Gets the value of the proofed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isProofed() {
        if (proofed == null) {
            return false;
        } else {
            return proofed;
        }
    }

    /**
     * Sets the value of the proofed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProofed(Boolean value) {
        this.proofed = value;
    }

    /**
     * Gets the value of the wordStart property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isWordStart() {
        if (wordStart == null) {
            return false;
        } else {
            return wordStart;
        }
    }

    /**
     * Sets the value of the wordStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWordStart(Boolean value) {
        this.wordStart = value;
    }

    /**
     * Gets the value of the wordFirst property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isWordFirst() {
        if (wordFirst == null) {
            return false;
        } else {
            return wordFirst;
        }
    }

    /**
     * Sets the value of the wordFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWordFirst(Boolean value) {
        this.wordFirst = value;
    }

    /**
     * Gets the value of the wordLeftMost property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isWordLeftMost() {
        if (wordLeftMost == null) {
            return false;
        } else {
            return wordLeftMost;
        }
    }

    /**
     * Sets the value of the wordLeftMost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWordLeftMost(Boolean value) {
        this.wordLeftMost = value;
    }

    /**
     * Gets the value of the wordFromDictionary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWordFromDictionary() {
        return wordFromDictionary;
    }

    /**
     * Sets the value of the wordFromDictionary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWordFromDictionary(Boolean value) {
        this.wordFromDictionary = value;
    }

    /**
     * Gets the value of the wordNormal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWordNormal() {
        return wordNormal;
    }

    /**
     * Sets the value of the wordNormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWordNormal(Boolean value) {
        this.wordNormal = value;
    }

    /**
     * Gets the value of the wordNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWordNumeric() {
        return wordNumeric;
    }

    /**
     * Sets the value of the wordNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWordNumeric(Boolean value) {
        this.wordNumeric = value;
    }

    /**
     * Gets the value of the wordIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWordIdentifier() {
        return wordIdentifier;
    }

    /**
     * Sets the value of the wordIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWordIdentifier(Boolean value) {
        this.wordIdentifier = value;
    }

    /**
     * Gets the value of the charConfidence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCharConfidence() {
        return charConfidence;
    }

    /**
     * Sets the value of the charConfidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCharConfidence(BigInteger value) {
        this.charConfidence = value;
    }

    /**
     * Gets the value of the serifProbability property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSerifProbability() {
        return serifProbability;
    }

    /**
     * Sets the value of the serifProbability property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSerifProbability(BigInteger value) {
        this.serifProbability = value;
    }

    /**
     * Gets the value of the wordPenalty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWordPenalty() {
        return wordPenalty;
    }

    /**
     * Sets the value of the wordPenalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWordPenalty(BigInteger value) {
        this.wordPenalty = value;
    }

    /**
     * Gets the value of the meanStrokeWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMeanStrokeWidth() {
        return meanStrokeWidth;
    }

    /**
     * Sets the value of the meanStrokeWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMeanStrokeWidth(BigInteger value) {
        this.meanStrokeWidth = value;
    }

    /**
     * Gets the value of the characterHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCharacterHeight() {
        return characterHeight;
    }

    /**
     * Sets the value of the characterHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCharacterHeight(BigInteger value) {
        this.characterHeight = value;
    }

    /**
     * Gets the value of the hasUncertainHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasUncertainHeight() {
        return hasUncertainHeight;
    }

    /**
     * Sets the value of the hasUncertainHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasUncertainHeight(Boolean value) {
        this.hasUncertainHeight = value;
    }

    /**
     * Gets the value of the baseLine property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBaseLine() {
        return baseLine;
    }

    /**
     * Sets the value of the baseLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBaseLine(BigInteger value) {
        this.baseLine = value;
    }

    /**
     * Gets the value of the isTab property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsTab() {
        if (isTab == null) {
            return false;
        } else {
            return isTab;
        }
    }

    /**
     * Sets the value of the isTab property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTab(Boolean value) {
        this.isTab = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="charRecVariant" type="{http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml}CharRecognitionVariant" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "charRecVariant"
    })
    public static class CharRecVariants {

        protected List<CharRecognitionVariant> charRecVariant;

        /**
         * Gets the value of the charRecVariant property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the charRecVariant property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCharRecVariant().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CharRecognitionVariant }
         * 
         * 
         */
        public List<CharRecognitionVariant> getCharRecVariant() {
            if (charRecVariant == null) {
                charRecVariant = new ArrayList<CharRecognitionVariant>();
            }
            return this.charRecVariant;
        }

    }

}
