//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 01:41:32 PM CEST 
//


package org.mycore.xml.abbyy.v10;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mycore.abbyy.v10 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FormattingTypeCharParams_QNAME = new QName("http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", "charParams");
    private final static QName _FormattingTypeWordRecVariants_QNAME = new QName("http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", "wordRecVariants");
    private final static QName _CharParamsTypeCharRecVariants_QNAME = new QName("http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", "charRecVariants");
    private final static QName _SeparatorBlockTypeStart_QNAME = new QName("http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", "start");
    private final static QName _SeparatorBlockTypeEnd_QNAME = new QName("http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", "end");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mycore.abbyy.v10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link TextStreamType }
     * 
     */
    public TextStreamType createTextStreamType() {
        return new TextStreamType();
    }

    /**
     * Create an instance of {@link CharParamsType }
     * 
     */
    public CharParamsType createCharParamsType() {
        return new CharParamsType();
    }

    /**
     * Create an instance of {@link BlockType }
     * 
     */
    public BlockType createBlockType() {
        return new BlockType();
    }

    /**
     * Create an instance of {@link BlockType.Region }
     * 
     */
    public BlockType.Region createBlockTypeRegion() {
        return new BlockType.Region();
    }

    /**
     * Create an instance of {@link TableType }
     * 
     */
    public TableType createTableType() {
        return new TableType();
    }

    /**
     * Create an instance of {@link FormattingType }
     * 
     */
    public FormattingType createFormattingType() {
        return new FormattingType();
    }

    /**
     * Create an instance of {@link TableRowType }
     * 
     */
    public TableRowType createTableRowType() {
        return new TableRowType();
    }

    /**
     * Create an instance of {@link WordRecognitionVariant }
     * 
     */
    public WordRecognitionVariant createWordRecognitionVariant() {
        return new WordRecognitionVariant();
    }

    /**
     * Create an instance of {@link Document.DocumentData }
     * 
     */
    public Document.DocumentData createDocumentDocumentData() {
        return new Document.DocumentData();
    }

    /**
     * Create an instance of {@link Document.Page }
     * 
     */
    public Document.Page createDocumentPage() {
        return new Document.Page();
    }

    /**
     * Create an instance of {@link PageSectionType }
     * 
     */
    public PageSectionType createPageSectionType() {
        return new PageSectionType();
    }

    /**
     * Create an instance of {@link ParagraphType }
     * 
     */
    public ParagraphType createParagraphType() {
        return new ParagraphType();
    }

    /**
     * Create an instance of {@link CaptionType }
     * 
     */
    public CaptionType createCaptionType() {
        return new CaptionType();
    }

    /**
     * Create an instance of {@link PageElementType }
     * 
     */
    public PageElementType createPageElementType() {
        return new PageElementType();
    }

    /**
     * Create an instance of {@link SeparatorBlockType }
     * 
     */
    public SeparatorBlockType createSeparatorBlockType() {
        return new SeparatorBlockType();
    }

    /**
     * Create an instance of {@link LineType }
     * 
     */
    public LineType createLineType() {
        return new LineType();
    }

    /**
     * Create an instance of {@link PageStreamType }
     * 
     */
    public PageStreamType createPageStreamType() {
        return new PageStreamType();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link CharRecognitionVariant }
     * 
     */
    public CharRecognitionVariant createCharRecognitionVariant() {
        return new CharRecognitionVariant();
    }

    /**
     * Create an instance of {@link FontStyleType }
     * 
     */
    public FontStyleType createFontStyleType() {
        return new FontStyleType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link SectionType }
     * 
     */
    public SectionType createSectionType() {
        return new SectionType();
    }

    /**
     * Create an instance of {@link PictureType }
     * 
     */
    public PictureType createPictureType() {
        return new PictureType();
    }

    /**
     * Create an instance of {@link ParagraphStyleType }
     * 
     */
    public ParagraphStyleType createParagraphStyleType() {
        return new ParagraphStyleType();
    }

    /**
     * Create an instance of {@link BarcodeType }
     * 
     */
    public BarcodeType createBarcodeType() {
        return new BarcodeType();
    }

    /**
     * Create an instance of {@link BarcodeInfoType }
     * 
     */
    public BarcodeInfoType createBarcodeInfoType() {
        return new BarcodeInfoType();
    }

    /**
     * Create an instance of {@link TextStreamType.MainText }
     * 
     */
    public TextStreamType.MainText createTextStreamTypeMainText() {
        return new TextStreamType.MainText();
    }

    /**
     * Create an instance of {@link TextStreamType.ElemId }
     * 
     */
    public TextStreamType.ElemId createTextStreamTypeElemId() {
        return new TextStreamType.ElemId();
    }

    /**
     * Create an instance of {@link CharParamsType.CharRecVariants }
     * 
     */
    public CharParamsType.CharRecVariants createCharParamsTypeCharRecVariants() {
        return new CharParamsType.CharRecVariants();
    }

    /**
     * Create an instance of {@link BlockType.SeparatorsBox }
     * 
     */
    public BlockType.SeparatorsBox createBlockTypeSeparatorsBox() {
        return new BlockType.SeparatorsBox();
    }

    /**
     * Create an instance of {@link BlockType.Region.Rect }
     * 
     */
    public BlockType.Region.Rect createBlockTypeRegionRect() {
        return new BlockType.Region.Rect();
    }

    /**
     * Create an instance of {@link TableType.TableCell }
     * 
     */
    public TableType.TableCell createTableTypeTableCell() {
        return new TableType.TableCell();
    }

    /**
     * Create an instance of {@link FormattingType.WordRecVariants }
     * 
     */
    public FormattingType.WordRecVariants createFormattingTypeWordRecVariants() {
        return new FormattingType.WordRecVariants();
    }

    /**
     * Create an instance of {@link TableRowType.Cell }
     * 
     */
    public TableRowType.Cell createTableRowTypeCell() {
        return new TableRowType.Cell();
    }

    /**
     * Create an instance of {@link WordRecognitionVariant.VariantText }
     * 
     */
    public WordRecognitionVariant.VariantText createWordRecognitionVariantVariantText() {
        return new WordRecognitionVariant.VariantText();
    }

    /**
     * Create an instance of {@link Document.DocumentData.ParagraphStyles }
     * 
     */
    public Document.DocumentData.ParagraphStyles createDocumentDocumentDataParagraphStyles() {
        return new Document.DocumentData.ParagraphStyles();
    }

    /**
     * Create an instance of {@link Document.DocumentData.Sections }
     * 
     */
    public Document.DocumentData.Sections createDocumentDocumentDataSections() {
        return new Document.DocumentData.Sections();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CharParamsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", name = "charParams", scope = FormattingType.class)
    public JAXBElement<CharParamsType> createFormattingTypeCharParams(CharParamsType value) {
        return new JAXBElement<CharParamsType>(_FormattingTypeCharParams_QNAME, CharParamsType.class, FormattingType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormattingType.WordRecVariants }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", name = "wordRecVariants", scope = FormattingType.class)
    public JAXBElement<FormattingType.WordRecVariants> createFormattingTypeWordRecVariants(FormattingType.WordRecVariants value) {
        return new JAXBElement<FormattingType.WordRecVariants>(_FormattingTypeWordRecVariants_QNAME, FormattingType.WordRecVariants.class, FormattingType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CharParamsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", name = "charParams", scope = WordRecognitionVariant.VariantText.class)
    public JAXBElement<CharParamsType> createWordRecognitionVariantVariantTextCharParams(CharParamsType value) {
        return new JAXBElement<CharParamsType>(_FormattingTypeCharParams_QNAME, CharParamsType.class, WordRecognitionVariant.VariantText.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CharParamsType.CharRecVariants }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", name = "charRecVariants", scope = CharParamsType.class)
    public JAXBElement<CharParamsType.CharRecVariants> createCharParamsTypeCharRecVariants(CharParamsType.CharRecVariants value) {
        return new JAXBElement<CharParamsType.CharRecVariants>(_CharParamsTypeCharRecVariants_QNAME, CharParamsType.CharRecVariants.class, CharParamsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Point }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", name = "start", scope = SeparatorBlockType.class)
    public JAXBElement<Point> createSeparatorBlockTypeStart(Point value) {
        return new JAXBElement<Point>(_SeparatorBlockTypeStart_QNAME, Point.class, SeparatorBlockType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Point }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", name = "end", scope = SeparatorBlockType.class)
    public JAXBElement<Point> createSeparatorBlockTypeEnd(Point value) {
        return new JAXBElement<Point>(_SeparatorBlockTypeEnd_QNAME, Point.class, SeparatorBlockType.class, value);
    }

}
