//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 01:41:32 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.mycore.xml.abbyy.v10;
