//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 01:41:32 PM CEST 
//


package org.mycore.xml.abbyy.v10;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParagraphAlignment.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParagraphAlignment">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Left"/>
 *     &lt;enumeration value="Center"/>
 *     &lt;enumeration value="Right"/>
 *     &lt;enumeration value="Justified"/>
 *     &lt;enumeration value="CjkJustified"/>
 *     &lt;enumeration value="ThaiJustified"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ParagraphAlignment")
@XmlEnum
public enum ParagraphAlignment {

    @XmlEnumValue("Left")
    LEFT("Left"),
    @XmlEnumValue("Center")
    CENTER("Center"),
    @XmlEnumValue("Right")
    RIGHT("Right"),
    @XmlEnumValue("Justified")
    JUSTIFIED("Justified"),
    @XmlEnumValue("CjkJustified")
    CJK_JUSTIFIED("CjkJustified"),
    @XmlEnumValue("ThaiJustified")
    THAI_JUSTIFIED("ThaiJustified");
    private final String value;

    ParagraphAlignment(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParagraphAlignment fromValue(String v) {
        for (ParagraphAlignment c: ParagraphAlignment.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
