//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 01:41:32 PM CEST 
//


package org.mycore.xml.abbyy.v10;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TableCellBorderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TableCellBorderType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Absent"/>
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="White"/>
 *     &lt;enumeration value="Black"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TableCellBorderType")
@XmlEnum
public enum TableCellBorderType {

    @XmlEnumValue("Absent")
    ABSENT("Absent"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("White")
    WHITE("White"),
    @XmlEnumValue("Black")
    BLACK("Black");
    private final String value;

    TableCellBorderType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TableCellBorderType fromValue(String v) {
        for (TableCellBorderType c: TableCellBorderType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
